In [ ]:
#1.Write a Python Program to Add Two Matrices?
#2. Write a Python Program to Multiply Two Matrices?
#3. Write a Python Program to Transpose a Matrix?
#4. Write a Python Program to Sort Words in Alphabetic Order?
#5. Write a Python Program to Remove Punctuation From a String?

In [28]:
A=[[1,2,3],
  [4,5,6],
  [7,8,9]]

B=[[12,34,22],
  [22,32,42],
  [43,44,45]]

result=[[0,0,0],
       [0,0,0],
       [0,0,0]]

for i in range(len(A)):
    for j in range(len(A[0])):
        result[i][j]=A[i][j]+B[i][j]
        
result



[[13, 36, 25], [26, 37, 48], [50, 52, 54]]

In [29]:
#2

A=[[1,2,3],
  [4,5,6],
  [7,8,9]]

B=[[12,34,22],
  [22,32,42],
  [43,44,45]]

result=[[0,0,0],
       [0,0,0],
       [0,0,0]]

for i in range(len(A)):
    for j in range(len(A[0])):
        result[i][j]=A[i][j]*B[i][j]
        
result



[[12, 68, 66], [88, 160, 252], [301, 352, 405]]

In [33]:
#1
import numpy as np
A=np.array([[1,2,3],[2,3,4],[4,5,6]])
B=np.array([[22,32,21],[12,13,14],[32,21,12]])
C=A+B
print (C)

[[23 34 24]
 [14 16 18]
 [36 26 18]]


In [34]:
#2
import numpy as np
A=np.array([[1,2,3],
            [2,3,4],
            [4,5,6]])
B=np.array([[22,32,21],
            [12,13,14],
            [32,21,12]])
C=A*B
print (C)

[[ 22  64  63]
 [ 24  39  56]
 [128 105  72]]


In [40]:
#3

import numpy as np
M=np.array([[1,2,88],
            [3,4,65],
            [5,6,55]])
M1=np.transpose(M)
M1

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [88, 65, 55]])

In [48]:
#4
str=input("Enter your string:"  )
words=str.split()

words.sort()

for i in words:
    print(i)

Enter your string:This is my eighth assignment 
This
assignment
eighth
is
my


In [54]:
#5

str1=input("enter your string:"  )

punc='''!()-[]{};:'"\, <>./?@#$%^&*_~'''

for i in str1:
    if i in punc:
        str1=str1.replace(i," ")
print (str1)


enter your string:Pycharm@is#a.good%platform
Pycharm is a good platform
